import { DebateMessage } from './constants';
import { format } from 'date-fns';

/**
 * Export debate transcript to plain text format
 */
export function exportDebateTranscript(
  messages: DebateMessage[],
  topicTitle: string,
  topicDescription: string
): void {
  const timestamp = format(new Date(), 'yyyy-MM-dd_HH-mm-ss');
  const filename = `debate-transcript_${timestamp}.txt`;
  
  // Build the transcript content
  const lines: string[] = [];
  
  // Header
  lines.push('='.repeat(80));
  lines.push('THERAPIST ROUNDTABLE DEBATE TRANSCRIPT');
  lines.push('='.repeat(80));
  lines.push('');
  lines.push(`Topic: ${topicTitle}`);
  lines.push(`Description: ${topicDescription}`);
  lines.push(`Date: ${format(new Date(), 'MMMM d, yyyy')}`);
  lines.push(`Time: ${format(new Date(), 'h:mm a')}`);
  lines.push(`Total Messages: ${messages.length}`);
  lines.push('');
  lines.push('='.repeat(80));
  lines.push('');
  
  // Participants
  const participants = new Set<string>();
  messages.forEach(msg => participants.add(msg.speaker));
  
  lines.push('PARTICIPANTS:');
  participants.forEach(participant => {
    if (participant === 'Dr. Sarah') {
      lines.push('  • Dr. Sarah - CBT Therapist');
    } else if (participant === 'Dr. Laura') {
      lines.push('  • Dr. Laura - Psychoanalytic Therapist');
    } else if (participant === 'Dr. John') {
      lines.push('  • Dr. John - Mindfulness Therapist');
    } else if (participant === 'User') {
      lines.push('  • User - Participant');
    }
  });
  lines.push('');
  lines.push('='.repeat(80));
  lines.push('');
  
  // Messages
  lines.push('TRANSCRIPT:');
  lines.push('');
  
  messages.forEach((message, index) => {
    const time = format(message.timestamp, 'h:mm:ss a');
    const speaker = message.speaker.toUpperCase();
    
    lines.push(`[${index + 1}] ${time} - ${speaker}`);
    lines.push('-'.repeat(80));
    
    // Wrap long messages
    const words = message.message.split(' ');
    let currentLine = '';
    
    words.forEach(word => {
      if ((currentLine + word).length > 76) {
        lines.push(currentLine.trim());
        currentLine = word + ' ';
      } else {
        currentLine += word + ' ';
      }
    });
    
    if (currentLine.trim()) {
      lines.push(currentLine.trim());
    }
    
    lines.push('');
  });
  
  // Footer
  lines.push('='.repeat(80));
  lines.push('END OF TRANSCRIPT');
  lines.push('='.repeat(80));
  lines.push('');
  lines.push('Generated by Solace');
  lines.push(`Export Date: ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}`);
  
  // Create blob and download
  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  // Create temporary link and trigger download
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Format a timestamp for display
 */
export function formatTimestamp(date: Date): string {
  return format(date, 'h:mm a');
}

/**
 * Get relative time (e.g., "2 minutes ago")
 */
export function getRelativeTime(date: Date): string {
  const now = new Date();
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  
  if (diffInSeconds < 60) {
    return 'just now';
  }
  
  const diffInMinutes = Math.floor(diffInSeconds / 60);
  if (diffInMinutes < 60) {
    return `${diffInMinutes} ${diffInMinutes === 1 ? 'minute' : 'minutes'} ago`;
  }
  
  const diffInHours = Math.floor(diffInMinutes / 60);
  if (diffInHours < 24) {
    return `${diffInHours} ${diffInHours === 1 ? 'hour' : 'hours'} ago`;
  }
  
  return format(date, 'MMM d, yyyy');
}

/**
 * Export debate transcript to Markdown format
 */
export function exportToMarkdown(
  messages: DebateMessage[],
  topicTitle: string,
  topicDescription: string
): void {
  const timestamp = format(new Date(), 'yyyy-MM-dd_HH-mm-ss');
  const filename = `debate-transcript_${timestamp}.md`;
  
  // Build the markdown content
  const lines: string[] = [];
  
  // Header
  lines.push('# Therapist Roundtable Debate Transcript\n');
  lines.push(`## ${topicTitle}\n`);
  lines.push(`**Description:** ${topicDescription}\n`);
  lines.push(`**Date:** ${format(new Date(), 'MMMM d, yyyy')}`);
  lines.push(`**Time:** ${format(new Date(), 'h:mm a')}`);
  lines.push(`**Total Messages:** ${messages.length}\n`);
  lines.push('---\n');
  
  // Participants
  const participants = new Set<string>();
  messages.forEach(msg => participants.add(msg.speaker));
  
  lines.push('## Participants\n');
  participants.forEach(participant => {
    if (participant === 'Dr. Sarah') {
      lines.push('- **Dr. Sarah** - CBT Therapist');
    } else if (participant === 'Dr. Laura') {
      lines.push('- **Dr. Laura** - Psychoanalytic Therapist');
    } else if (participant === 'Dr. John') {
      lines.push('- **Dr. John** - Mindfulness Therapist');
    } else if (participant === 'User') {
      lines.push('- **User** - Participant');
    }
  });
  lines.push('\n---\n');
  
  // Messages
  lines.push('## Transcript\n');
  
  messages.forEach((message, index) => {
    const time = format(message.timestamp, 'h:mm:ss a');
    const speaker = message.speaker;
    
    lines.push(`### ${index + 1}. ${speaker} *[${time}]*\n`);
    lines.push(`${message.message}\n`);
  });
  
  // Footer
  lines.push('\n---\n');
  lines.push('*Generated by Solace*\n');
  lines.push(`*Export Date: ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}*`);
  
  // Create blob and download
  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  // Create temporary link and trigger download
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export debate transcript to PDF format (using HTML to PDF conversion)
 */
export function exportToPDF(
  messages: DebateMessage[],
  topicTitle: string,
  topicDescription: string
): void {
  const timestamp = format(new Date(), 'yyyy-MM-dd_HH-mm-ss');
  const filename = `debate-transcript_${timestamp}.pdf`;
  
  // Build HTML content for PDF
  const participants = new Set<string>();
  messages.forEach(msg => participants.add(msg.speaker));
  
  const participantsList = Array.from(participants).map(participant => {
    if (participant === 'Dr. Sarah') return '<li><strong>Dr. Sarah</strong> - CBT Therapist</li>';
    if (participant === 'Dr. Laura') return '<li><strong>Dr. Laura</strong> - Psychoanalytic Therapist</li>';
    if (participant === 'Dr. John') return '<li><strong>Dr. John</strong> - Mindfulness Therapist</li>';
    if (participant === 'User') return '<li><strong>User</strong> - Participant</li>';
    return '';
  }).join('');
  
  const messagesList = messages.map((message, index) => {
    const time = format(message.timestamp, 'h:mm:ss a');
    const speakerColor = 
      message.speaker === 'Dr. Sarah' ? '#3b82f6' :
      message.speaker === 'Dr. Laura' ? '#8b5cf6' :
      message.speaker === 'Dr. John' ? '#10b981' :
      '#6366f1';
    
    return `
      <div style="margin-bottom: 24px; page-break-inside: avoid;">
        <div style="display: flex; align-items: center; margin-bottom: 8px;">
          <span style="font-weight: 600; color: ${speakerColor}; margin-right: 8px;">${message.speaker}</span>
          <span style="color: #6b7280; font-size: 12px;">[${time}]</span>
        </div>
        <div style="background: #f9fafb; padding: 16px; border-radius: 8px; border-left: 4px solid ${speakerColor};">
          <p style="margin: 0; line-height: 1.6; color: #1f2937;">${message.message}</p>
        </div>
      </div>
    `;
  }).join('');
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${topicTitle}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          color: #1f2937;
          background: white;
        }
        h1 {
          color: #111827;
          border-bottom: 3px solid #3b82f6;
          padding-bottom: 16px;
          margin-bottom: 24px;
        }
        h2 {
          color: #374151;
          margin-top: 32px;
          margin-bottom: 16px;
        }
        .metadata {
          background: #f3f4f6;
          padding: 16px;
          border-radius: 8px;
          margin-bottom: 24px;
        }
        .metadata p {
          margin: 4px 0;
          color: #4b5563;
        }
        ul {
          list-style: none;
          padding: 0;
        }
        ul li {
          padding: 8px 0;
          border-bottom: 1px solid #e5e7eb;
        }
        .footer {
          margin-top: 48px;
          padding-top: 24px;
          border-top: 2px solid #e5e7eb;
          text-align: center;
          color: #6b7280;
          font-size: 14px;
        }
        @media print {
          body {
            padding: 20px;
          }
        }
      </style>
    </head>
    <body>
      <h1>Therapist Roundtable Debate Transcript</h1>
      
      <div class="metadata">
        <p><strong>Topic:</strong> ${topicTitle}</p>
        <p><strong>Description:</strong> ${topicDescription}</p>
        <p><strong>Date:</strong> ${format(new Date(), 'MMMM d, yyyy')}</p>
        <p><strong>Time:</strong> ${format(new Date(), 'h:mm a')}</p>
        <p><strong>Total Messages:</strong> ${messages.length}</p>
      </div>
      
      <h2>Participants</h2>
      <ul>
        ${participantsList}
      </ul>
      
      <h2>Transcript</h2>
      ${messagesList}
      
      <div class="footer">
        <p>Generated by Solace</p>
        <p>Export Date: ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}</p>
      </div>
    </body>
    </html>
  `;
  
  // Create a new window and print to PDF
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load then trigger print
    printWindow.onload = () => {
      printWindow.print();
      // Note: User will need to select "Save as PDF" in their print dialog
    };
  } else {
    alert('Please allow pop-ups to export to PDF');
  }
}
