import { DebateMessage } from './constants';
import { format } from 'date-fns';

/**
 * Export debate transcript to plain text format
 */
export function exportDebateTranscript(
  messages: DebateMessage[],
  topicTitle: string,
  topicDescription: string
): void {
  const timestamp = format(new Date(), 'yyyy-MM-dd_HH-mm-ss');
  const filename = `debate-transcript_${timestamp}.txt`;
  
  // Build the transcript content
  const lines: string[] = [];
  
  // Header
  lines.push('='.repeat(80));
  lines.push('THERAPIST ROUNDTABLE DEBATE TRANSCRIPT');
  lines.push('='.repeat(80));
  lines.push('');
  lines.push(`Topic: ${topicTitle}`);
  lines.push(`Description: ${topicDescription}`);
  lines.push(`Date: ${format(new Date(), 'MMMM d, yyyy')}`);
  lines.push(`Time: ${format(new Date(), 'h:mm a')}`);
  lines.push(`Total Messages: ${messages.length}`);
  lines.push('');
  lines.push('='.repeat(80));
  lines.push('');
  
  // Participants
  const participants = new Set<string>();
  messages.forEach(msg => participants.add(msg.speaker));
  
  lines.push('PARTICIPANTS:');
  participants.forEach(participant => {
    if (participant === 'Dr. Sarah') {
      lines.push('  • Dr. Sarah - CBT Therapist');
    } else if (participant === 'Dr. Laura') {
      lines.push('  • Dr. Laura - Psychoanalytic Therapist');
    } else if (participant === 'Dr. John') {
      lines.push('  • Dr. John - Mindfulness Therapist');
    } else if (participant === 'User') {
      lines.push('  • User - Participant');
    }
  });
  lines.push('');
  lines.push('='.repeat(80));
  lines.push('');
  
  // Messages
  lines.push('TRANSCRIPT:');
  lines.push('');
  
  messages.forEach((message, index) => {
    const time = format(message.timestamp, 'h:mm:ss a');
    const speaker = message.speaker.toUpperCase();
    
    lines.push(`[${index + 1}] ${time} - ${speaker}`);
    lines.push('-'.repeat(80));
    
    // Wrap long messages
    const words = message.message.split(' ');
    let currentLine = '';
    
    words.forEach(word => {
      if ((currentLine + word).length > 76) {
        lines.push(currentLine.trim());
        currentLine = word + ' ';
      } else {
        currentLine += word + ' ';
      }
    });
    
    if (currentLine.trim()) {
      lines.push(currentLine.trim());
    }
    
    lines.push('');
  });
  
  // Footer
  lines.push('='.repeat(80));
  lines.push('END OF TRANSCRIPT');
  lines.push('='.repeat(80));
  lines.push('');
  lines.push('Generated by Solace');
  lines.push(`Export Date: ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}`);
  
  // Create blob and download
  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  // Create temporary link and trigger download
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Format a timestamp for display
 */
export function formatTimestamp(date: Date): string {
  return format(date, 'h:mm a');
}

/**
 * Get relative time (e.g., "2 minutes ago")
 */
export function getRelativeTime(date: Date): string {
  const now = new Date();
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  
  if (diffInSeconds < 60) {
    return 'just now';
  }
  
  const diffInMinutes = Math.floor(diffInSeconds / 60);
  if (diffInMinutes < 60) {
    return `${diffInMinutes} ${diffInMinutes === 1 ? 'minute' : 'minutes'} ago`;
  }
  
  const diffInHours = Math.floor(diffInMinutes / 60);
  if (diffInHours < 24) {
    return `${diffInHours} ${diffInHours === 1 ? 'hour' : 'hours'} ago`;
  }
  
  return format(date, 'MMM d, yyyy');
}
